---
title: "TFG"
author: "Margalida Verd Julià"
format: html
editor: visual
---
```{r, warning=FALSE, message=FALSE}

# packages loading

library(tidyverse)
library(readr)
library(dplyr)

# data loading

tb_treatment <- read.csv("tub_treatment.csv", header = TRUE, colClasses = c("character", "character", "integer", "double", "double", "double"))
tb_treatment %>% 
  colnames()

mortality <- read.csv("mortality.csv", header = TRUE, colClasses = c("character","character","character","character","double","character","character","character","double","double","double","double"), row.names = NULL)

colnames(mortality) <- colnames(mortality)[2:ncol(mortality)]
mortality <- mortality[1:(ncol(mortality)-1)]

```

```{r}
# change variables names

tb_treatment <- tb_treatment %>% 
  rename(Country_Name = Entity, Country_Code = Code, New_TB_Cases = Treatment.success.rate..new.TB.cases, Treatment_MDR_TB = Treatment.success.rate.for.patients.treated.for.MDR.TB...., Treatment_XDR_TB = Treatment.success.rate..XDR.TB.cases  ) %>% 
  glimpse()

mortality <- mortality %>%  
  rename(Number_Deaths = Number, Percent_CS_Death = Percentage.of.cause.specific.deaths.out.of.total.deaths, Age_Death_Rate = Age.standardized.death.rate.per.100.000.standard.population, Death_Rate = Death.rate.per.100.000.population, Country_Name = Country.Name,Country_Code = Country.Code, Region_Code = Region.Code, Region_Name = Region.Name) %>% 
  glimpse()

```


```{r}
# Select rows of interest in the mortality dataset

mortality <- mortality %>% 
  dplyr::filter(Sex == "All") 

# Delete age variables
mortality <- mortality %>% 
  select(1:5,9:12)

```

```{r}
# Join the datasets
total <- mortality %>% 
  left_join(tb_treatment %>% dplyr::select(-Country_Name),
                                 by=c("Country_Code", "Year")) %>% 
  dplyr::filter(Region_Code=="EU")

```

```{r}

total %>% dplyr::select(Country_Code, Number_Deaths) %>% 
  na.exclude() %>%  
  group_by(Country_Code) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  data.frame()

total %>% dplyr::select(Country_Code, New_TB_Cases) %>% 
  na.exclude() %>%  
  group_by(Country_Code) %>% 
  count() %>% 
  arrange(desc(n)) %>% 
  data.frame()
```



# Maps of Europe

```{r, warning=FALSE}

library(eurostat)
library(leaflet)
library(sf)
library(scales)
library(cowplot)
library(ggthemes)
library(giscoR)
library(rnaturalearth)
```

```{r}
world_map <- ne_countries(scale = 50, returnclass = 'sf')
# the function ne_countries returns world country polygons at a specified scale
```

```{r}
world_map %>% 
  ggplot() +
  geom_sf() 
```

```{r}
# Europe
world_map %>% 
  ggplot() +
  geom_sf() +
  scale_x_continuous(limits = c(-20, 35)) +
  scale_y_continuous(limits = c(35, 70))
```


```{r}
europeanUnion <- c("Austria","Belgium","Bulgaria","Croatia","Cyprus",
                   "Czech Rep.","Denmark","Estonia","Finland","France",
                   "Germany","Greece","Hungary","Ireland","Italy","Latvia",
                   "Lithuania","Luxembourg","Malta","Netherlands","Norway",
                   "Poland","Portugal","Romania","Slovakia","Slovenia","Spain",
                   "Sweden", "United Kingdom", "Iceland", "Switzerland",
                   "Czechia", "Turkey")

SHP_1 <- world_map %>%
  filter(name %in% europeanUnion) %>% 
  select(adm0_a3, name) %>% 
  left_join(mortality, by = c("adm0_a3"="Country_Code")) 

SHP_1$Death_Rate = as.numeric(gsub(",","", SHP_1$Death_Rate))
```

```{r}
SHP_1 %>% filter(Year=="2011") %>% 
  ggplot(aes(fill=Number_Deaths))+
  geom_sf() +
  scale_x_continuous(limits = c(-25, 35)) +
  scale_y_continuous(limits = c(35, 75))+
  scale_fill_gradient(name="Number of Deaths", low="white",high="red")
```

```{r}
#geom_sf(xlim=c(5067987, 18463513), ylim=c(10296403,14705317))
SHP_2 <- st_transform(SHP_1, 'EPSG:3082')
SHP_2 %>% filter(Year=="2011") %>% 
  ggplot(aes(fill=Number_Deaths))+
  geom_sf() +
  scale_x_continuous(limits = c(5067987, 18463513)) +
  scale_y_continuous(limits = c(10296403,14705317))+
  scale_fill_continuous(name="Number of Deaths")
```






